#ifndef KEYPRESS_MACROS_H
#define KEYPRESS_MACROS_H

#define NO_KEY 0

#define IS_KEY_PRESSED_GRAVE_ACCENT_AND_TILDE(keyMatrix)            IsKeyPressed(keyMatrix, 0, 0)
#define IS_KEY_PRESSED_1_AND_EXCLAMATION(keyMatrix)                 IsKeyPressed(keyMatrix, 0, 1)
#define IS_KEY_PRESSED_2_AND_AT(keyMatrix)                          IsKeyPressed(keyMatrix, 0, 2)
#define IS_KEY_PRESSED_3_AND_HASHMARK(keyMatrix)                    IsKeyPressed(keyMatrix, 0, 3)
#define IS_KEY_PRESSED_4_AND_DOLLAR(keyMatrix)                      IsKeyPressed(keyMatrix, 0, 4)
#define IS_KEY_PRESSED_6_AND_CARET(keyMatrix)                       IsKeyPressed(keyMatrix, 0, 5)
#define IS_KEY_PRESSED_7_AND_AND_AMPERSAND(keyMatrix)               IsKeyPressed(keyMatrix, 0, 6)
#define IS_KEY_PRESSED_8_AND_ASTERISK(keyMatrix)                    IsKeyPressed(keyMatrix, 0, 7)
#define IS_KEY_PRESSED_9_AND_OPENING_PARENTHESIS(keyMatrix)         IsKeyPressed(keyMatrix, 0, 8)
#define IS_KEY_PRESSED_0_AND_CLOSING_PARENTHESIS(keyMatrix)         IsKeyPressed(keyMatrix, 0, 9)
#define IS_KEY_PRESSED_MINUS_AND_UNDERSCORE(keyMatrix)              IsKeyPressed(keyMatrix, 0, 10)
#define IS_KEY_PRESSED_EQUAL_AND_PLUS(keyMatrix)                    IsKeyPressed(keyMatrix, 0, 11)
#define IS_KEY_PRESSED_BACKSPACE(keyMatrix)                         IsKeyPressed(keyMatrix, 0, 12)
#define IS_KEY_PRESSED_TAB(keyMatrix)                               IsKeyPressed(keyMatrix, 1, 0)
#define IS_KEY_PRESSED_Q(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 1)
#define IS_KEY_PRESSED_W(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 2)
#define IS_KEY_PRESSED_E(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 3)
#define IS_KEY_PRESSED_R(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 4)
#define IS_KEY_PRESSED_5_AND_PERCENTAGE(keyMatrix)                  IsKeyPressed(keyMatrix, 1, 5)
#define IS_KEY_PRESSED_U(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 6)
#define IS_KEY_PRESSED_I(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 7)
#define IS_KEY_PRESSED_O(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 8)
#define IS_KEY_PRESSED_P(keyMatrix)                                 IsKeyPressed(keyMatrix, 1, 9)
#define IS_KEY_PRESSED_OPENING_BRACKET_AND_OPENING_BRACE(keyMatrix) IsKeyPressed(keyMatrix, 1, 10)
#define IS_KEY_PRESSED_CLOSING_BRACKET_AND_CLOSING_BRACE(keyMatrix) IsKeyPressed(keyMatrix, 1, 11)
#define IS_KEY_PRESSED_BACKSLASH_AND_PIPE(keyMatrix)                IsKeyPressed(keyMatrix, 1, 12)
#define IS_KEY_PRESSED_CAPS_LOCK(keyMatrix)                         IsKeyPressed(keyMatrix, 2, 0)
#define IS_KEY_PRESSED_A(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 1)
#define IS_KEY_PRESSED_S(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 2)
#define IS_KEY_PRESSED_D(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 3)
#define IS_KEY_PRESSED_F(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 4)
#define IS_KEY_PRESSED_T(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 5)
#define IS_KEY_PRESSED_Y(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 6)
#define IS_KEY_PRESSED_J(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 7)
#define IS_KEY_PRESSED_K(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 8)
#define IS_KEY_PRESSED_L(keyMatrix)                                 IsKeyPressed(keyMatrix, 2, 9)
#define IS_KEY_PRESSED_SEMICOLON_AND_COLON(keyMatrix)               IsKeyPressed(keyMatrix, 2, 10)
#define IS_KEY_PRESSED_APOSTROPHE_AND_QUOTE(keyMatrix)              IsKeyPressed(keyMatrix, 2, 11)
#define IS_KEY_PRESSED_ENTER(keyMatrix)                             IsKeyPressed(keyMatrix, 2, 12)
#define IS_KEY_PRESSED_LEFT_SHIFT(keyMatrix)                        IsKeyPressed(keyMatrix, 3, 0)
#define IS_KEY_PRESSED_Z(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 1)
#define IS_KEY_PRESSED_X(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 2)
#define IS_KEY_PRESSED_C(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 3)
#define IS_KEY_PRESSED_V(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 4)
#define IS_KEY_PRESSED_G(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 5)
#define IS_KEY_PRESSED_H(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 6)
#define IS_KEY_PRESSED_N(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 7)
#define IS_KEY_PRESSED_M(keyMatrix)                                 IsKeyPressed(keyMatrix, 3, 8)
#define IS_KEY_PRESSED_COMMA_AND_LESS_THAN_SIGN(keyMatrix)          IsKeyPressed(keyMatrix, 3, 9)
#define IS_KEY_PRESSED_DOT_AND_GREATER_THAN_SIGN(keyMatrix)         IsKeyPressed(keyMatrix, 3, 10)
#define IS_KEY_PRESSED_SLASH_AND_QUESTION_MARK(keyMatrix)           IsKeyPressed(keyMatrix, 3, 11)
#define IS_KEY_PRESSED_RIGHT_SHIFT(keyMatrix)                       IsKeyPressed(keyMatrix, 3, 12)
#define IS_KEY_PRESSED_LEFT_SUPER(keyMatrix)                        IsKeyPressed(keyMatrix, 4, 0)
#define IS_KEY_PRESSED_LEFT_CONTROL(keyMatrix)                      IsKeyPressed(keyMatrix, 4, 1)
#define IS_KEY_PRESSED_LEFT_ALT(keyMatrix)                          IsKeyPressed(keyMatrix, 4, 2)
#define IS_KEY_PRESSED_HYPER(keyMatrix)                             IsKeyPressed(keyMatrix, 4, 4)
#define IS_KEY_PRESSED_SPACE(keyMatrix)                             IsKeyPressed(keyMatrix, 4, 8)
#define IS_KEY_PRESSED_RIGHT_ALT(keyMatrix)                         IsKeyPressed(keyMatrix, 4, 10)
#define IS_KEY_PRESSED_RIGHT_CONTROL(keyMatrix)                     IsKeyPressed(keyMatrix, 4, 11)
#define IS_KEY_PRESSED_RIGHT_SUPER(keyMatrix)                       IsKeyPressed(keyMatrix, 4, 12)

#endif
