uint8_t hyperKeyMap[5][13] = {
    {  // Row 1
        HID_KEYBOARD_SC_ESCAPE,  // HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE
        HID_KEYBOARD_SC_F1,  // HID_KEYBOARD_SC_1_AND_EXCLAMATION
        HID_KEYBOARD_SC_F2,  // HID_KEYBOARD_SC_2_AND_AT
        HID_KEYBOARD_SC_F3,  // HID_KEYBOARD_SC_3_AND_HASHMARK
        HID_KEYBOARD_SC_F4,  // HID_KEYBOARD_SC_4_AND_DOLLAR
        HID_KEYBOARD_SC_F6,  // HID_KEYBOARD_SC_6_AND_CARET
        HID_KEYBOARD_SC_F7,  // HID_KEYBOARD_SC_7_AND_AND_AMPERSAND
        HID_KEYBOARD_SC_F8,  // HID_KEYBOARD_SC_8_AND_ASTERISK
        HID_KEYBOARD_SC_F9,  // HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS
        HID_KEYBOARD_SC_F10,  // HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS
        HID_KEYBOARD_SC_F11,  // HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE
        HID_KEYBOARD_SC_F12,  // HID_KEYBOARD_SC_EQUAL_AND_PLUS
        NO_KEY,  // HID_KEYBOARD_SC_BACKSPACE
    }, {  // Row 2
        NO_KEY,  // HID_KEYBOARD_SC_TAB
        NO_KEY,  // HID_KEYBOARD_SC_Q
        NO_KEY,  // HID_KEYBOARD_SC_W
        HID_KEYBOARD_SC_TAB,  // HID_KEYBOARD_SC_E
        HID_KEYBOARD_SC_TAB,  // HID_KEYBOARD_SC_R
        HID_KEYBOARD_SC_F5,  // HID_KEYBOARD_SC_5_AND_PERCENTAGE
        HID_KEYBOARD_SC_HOME,  // HID_KEYBOARD_SC_U
        HID_KEYBOARD_SC_UP_ARROW,  // HID_KEYBOARD_SC_I
        HID_KEYBOARD_SC_END,  // HID_KEYBOARD_SC_O
        HID_KEYBOARD_SC_DELETE,  // HID_KEYBOARD_SC_P
        NO_KEY,  // HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE
        NO_KEY,  // HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE
        NO_KEY,  // HID_KEYBOARD_SC_BACKSLASH_AND_PIPE
    }, {  // Row 3
        NO_KEY,  // HID_KEYBOARD_SC_CAPS_LOCK
        HID_KEYBOARD_SC_TAB,  // HID_KEYBOARD_SC_A
        HID_KEYBOARD_SC_A,  // HID_KEYBOARD_SC_S
        NO_KEY,  // HID_KEYBOARD_SC_D
        HID_KEYBOARD_SC_S,  // HID_KEYBOARD_SC_F
        NO_KEY,  // HID_KEYBOARD_SC_T
        HID_KEYBOARD_SC_PAGE_UP,  // HID_KEYBOARD_SC_Y
        HID_KEYBOARD_SC_LEFT_ARROW,  // HID_KEYBOARD_SC_J
        HID_KEYBOARD_SC_DOWN_ARROW,  // HID_KEYBOARD_SC_K
        HID_KEYBOARD_SC_RIGHT_ARROW,  // HID_KEYBOARD_SC_L
        HID_KEYBOARD_SC_ENTER,  // HID_KEYBOARD_SC_SEMICOLON_AND_COLON
        NO_KEY,  // HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE
        NO_KEY,  // HID_KEYBOARD_SC_ENTER
    }, {  // Row 4
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_SHIFT
        NO_KEY,  // HID_KEYBOARD_SC_Z
        NO_KEY,  // HID_KEYBOARD_SC_X
        NO_KEY,  // HID_KEYBOARD_SC_C
        NO_KEY,  // HID_KEYBOARD_SC_V
        NO_KEY,  // HID_KEYBOARD_SC_G
        HID_KEYBOARD_SC_PAGE_DOWN,  // HID_KEYBOARD_SC_H
        HID_KEYBOARD_SC_ESCAPE,  // HID_KEYBOARD_SC_N
        NO_KEY,  // HID_KEYBOARD_SC_M
        NO_KEY,  // HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN
        NO_KEY,  // HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN
        NO_KEY,  // HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_SHIFT
    }, {  // Row 5
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_GUI
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_CONTROL
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_ALT
        NO_KEY,  // NO_KEY
        NO_KEY,  // NO_KEY  // Hyper
        NO_KEY,  // HID_KEYBOARD_SC_B,
        NO_KEY,  // NO_KEY
        NO_KEY,  // NO_KEY
        NO_KEY,  // HID_KEYBOARD_SC_SPACE
        NO_KEY,  // NO_KEY
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_ALT
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_CONTROL
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_GUI
    }
};
