uint8_t sampleKeyMap[5][13] = {
    {  // Row 1
        NO_KEY,  // HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE
        NO_KEY,  // HID_KEYBOARD_SC_1_AND_EXCLAMATION
        NO_KEY,  // HID_KEYBOARD_SC_2_AND_AT
        NO_KEY,  // HID_KEYBOARD_SC_3_AND_HASHMARK
        NO_KEY,  // HID_KEYBOARD_SC_4_AND_DOLLAR
        NO_KEY,  // HID_KEYBOARD_SC_6_AND_CARET
        NO_KEY,  // HID_KEYBOARD_SC_7_AND_AND_AMPERSAND
        NO_KEY,  // HID_KEYBOARD_SC_8_AND_ASTERISK
        NO_KEY,  // HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS
        NO_KEY,  // HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS
        NO_KEY,  // HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE
        NO_KEY,  // HID_KEYBOARD_SC_EQUAL_AND_PLUS
        NO_KEY,  // HID_KEYBOARD_SC_BACKSPACE
    }, {  // Row 2
        NO_KEY,  // HID_KEYBOARD_SC_TAB
        NO_KEY,  // HID_KEYBOARD_SC_Q
        NO_KEY,  // HID_KEYBOARD_SC_W
        NO_KEY,  // HID_KEYBOARD_SC_E
        NO_KEY,  // HID_KEYBOARD_SC_R
        NO_KEY,  // HID_KEYBOARD_SC_5_AND_PERCENTAGE
        NO_KEY,  // HID_KEYBOARD_SC_U
        NO_KEY,  // HID_KEYBOARD_SC_I
        NO_KEY,  // HID_KEYBOARD_SC_O
        NO_KEY,  // HID_KEYBOARD_SC_P
        NO_KEY,  // HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE
        NO_KEY,  // HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE
        NO_KEY,  // HID_KEYBOARD_SC_BACKSLASH_AND_PIPE
    }, {  // Row 3
        NO_KEY,  // HID_KEYBOARD_SC_CAPS_LOCK
        NO_KEY,  // HID_KEYBOARD_SC_A
        NO_KEY,  // HID_KEYBOARD_SC_S
        NO_KEY,  // HID_KEYBOARD_SC_D
        NO_KEY,  // HID_KEYBOARD_SC_F
        NO_KEY,  // HID_KEYBOARD_SC_T
        NO_KEY,  // HID_KEYBOARD_SC_Y
        NO_KEY,  // HID_KEYBOARD_SC_J
        NO_KEY,  // HID_KEYBOARD_SC_K
        NO_KEY,  // HID_KEYBOARD_SC_L
        NO_KEY,  // HID_KEYBOARD_SC_SEMICOLON_AND_COLON
        NO_KEY,  // HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE
        NO_KEY,  // HID_KEYBOARD_SC_ENTER
    }, {  // Row 4
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_SHIFT
        NO_KEY,  // HID_KEYBOARD_SC_Z
        NO_KEY,  // HID_KEYBOARD_SC_X
        NO_KEY,  // HID_KEYBOARD_SC_C
        NO_KEY,  // HID_KEYBOARD_SC_V
        NO_KEY,  // HID_KEYBOARD_SC_G
        NO_KEY,  // HID_KEYBOARD_SC_H
        NO_KEY,  // HID_KEYBOARD_SC_N
        NO_KEY,  // HID_KEYBOARD_SC_M
        NO_KEY,  // HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN
        NO_KEY,  // HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN
        NO_KEY,  // HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_SHIFT
    }, {  // Row 5
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_GUI
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_CONTROL
        NO_KEY,  // HID_KEYBOARD_SC_LEFT_ALT
        NO_KEY,  // NO_KEY
        NO_KEY,  // NO_KEY  // Hyper
        NO_KEY,  // HID_KEYBOARD_SC_B,
        NO_KEY,  // NO_KEY
        NO_KEY,  // NO_KEY
        NO_KEY,  // HID_KEYBOARD_SC_SPACE
        NO_KEY,  // NO_KEY
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_ALT
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_CONTROL
        NO_KEY,  // HID_KEYBOARD_SC_RIGHT_GUI
    }
};
